# Generated by Django 4.0.6 on 2023-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='inch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
