# Generated by Django 4.0.6 on 2023-08-28 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_fertilizer_inch_alter_fertilizer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_name',
        ),
        migrations.AddField(
            model_name='package',
            name='inch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.fertilizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
