# Generated by Django 4.0.6 on 2023-08-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_package_package_remove_package_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inch', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem_Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.package')),
            ],
        ),
    ]
